### ISSUE TITLE
Site bet365 não está carregando

### ISSUE THREAD

**Issue by helmarjunior** [JDaniloC/Individual-Bet365Bot#10]
Acredito que a bet365 implementou bloqueios para ferramentas como Selenium, pois o site nao carrega. Tentei rodar esse bot hoje e o site da bet365 (https://www.bet365.com/) nao carregou, impedindo o bot de funcionar. Voces conseguiram contornar esse problema? 

Obrigado!

**Comment by JDaniloC** [comment]
Você está usando o Chrome ou Firefox?

**Comment by helmarjunior** [comment]
Tentei com ambos rodando separadamente, mas com o seu código tentei rodar no Firefox. 

Caso esteja funcionando em seu ambiente, por favor me diga a versão do Firefox/GeckDriver e se alguma configuração extra foi feita.

obrigado!

**Comment by JDaniloC** [comment]
Testei agora no Firefox 85.0.2 e funcionou, então atualizei para 88.0.1 e voltou a aparecer o ícone de bot, então parou de carregar.
Se quiser ajudar, modifique o widgets.py de forma a fingir que o Firefox não seja um bot (o ideal), ou volte a versão indicada.
Em caso positivo, pode fechar esta issue com o feedback, seja com a modificação do widgets.py ou um aviso no README de versão máxima.

**Comment by helmarjunior** [comment]
Obrigado pelo feedback @JDaniloC. 
Fiz o test usando a versao atual do Firefox e setando as configuracoes abaixo e nao funcionou: 
`
profile.set_preference("dom.webdriver.enabled", False)
profile.set_preference('useAutomationExtension', False)`

Jah com a versao 85.0.2 funcionou perfeitamente.
