### ISSUE TITLE
ERRO NA  CONEXÃO

### ISSUE THREAD

**Issue by OEDOARDO** [JDaniloC/Individual-Bet365Bot#12]
Boa noite,

Estou com erro quando incluo a linha MongoDB.cadastrar("NOMEDOUSUARIO", "SENHA"), Atlas error code 8000. Como posso solucionar?

**Comment by JDaniloC** [comment]
Ele não tá conseguindo entrar no collection do seu Mongo, está dando "bad auth : Authentication failed", verifique se você colocou a senha correta na conexão do Mongo.

**Comment by JDaniloC** [comment]
Solução do problema:

Ao criar a autenticação de um cluster mongo, exemplo:
usuario = testeUser
senha = senhaUser
cluster = 123

`
autenticacao = "mongodb+srv://testeUser:<SENHAMONGO>@cluster123.mongodb.net/betbot?retryWrites=true&w=majority"
`

A senha deve ser: 
`mongodb+srv://testeUser:senhaUser@cluster123.mongodb.net/betbot?retryWrites=true&w=majority`

Ao invez de:
`mongodb+srv://testeUser:<senhaUser>@cluster123.mongodb.net/betbot?retryWrites=true&w=majority`
