### ISSUE TITLE
Não finaliza a aposta

### ISSUE THREAD

**Issue by OEDOARDO** [JDaniloC/Individual-Bet365Bot#15]
O programa está funcionando normalmente até chegar a hora de adicionar o valor da aposta, ele encontra o jogo, contudo, a tela de colocar o valor fica aberta, sem adição. ![IMG_20210719_064132_035.jpg](https://user-images.githubusercontent.com/70857741/126139867-f5898778-3140-4d74-ba15-f5a80c3af150.jpg)

**Comment by JDaniloC** [comment]
A IQ mudou o visual da caixa de apostas, a antiga caixa de apostas é o formato que está no bot. É necessário refazer as funções de realizar operação.
