### ISSUE TITLE
ISSUE INSTALLING

### ISSUE THREAD

**Issue by byDrizzy** [JDaniloC/Individual-Bet365Bot#18]
Hey everybody, i have an issue installing some dependencies of the program. Anyone can help me setting up?
![OTHER BEt365](https://user-images.githubusercontent.com/95592412/147395639-bcc4416d-3016-493e-be1c-7f84288cef67.png)

**Comment by JDaniloC** [comment]
Try to remove greenlet from requirements.txt (probably isn't compatible with 3.10 version)

**Comment by JDaniloC** [comment]
If not works, just back to python 3.7-3.9 version
