### ISSUE TITLE
Bot ainda operacional?

### ISSUE THREAD

**Issue by julioflima** [JDaniloC/Individual-Bet365Bot#19]

**Comment by JDaniloC** [comment]
Nunca foi operacional, ele funcionava pra procurar uma aposta e realizar a aposta. Mas nunca foi usado de forma séria, e sabendo que iria dar muito trabalho, eu desisti de continuar.

**Comment by julioflima** [comment]
Certo, mas isso que tu descreveste ainda funciona?

Podes testar e me dar uma resposta?

**Comment by JDaniloC** [comment]
Acredito que não funciona completamente por que a Bet365 atualizou a interface, e atualizando a interface quebra o bot, obrigando a atualizar o bot também.
