### ISSUE TITLE
Como o bot analisa as apostas

### ISSUE THREAD

**Issue by rodrigobg** [JDaniloC/Individual-Bet365Bot#20]
Olá tudo bem? Em primeiro lugar quero te dar os parabéns pelo projeto. 
mas gostaria de entender mais como o bot analisa os jogos e efetua as apostas, existe alguma função no Python pra isso? Aguardo seu contato e parabéns pelo projeto.

**Comment by JDaniloC** [comment]
O bot não analisa as apostas, você escolhe a disposição de jogo, por exemplo:
Gols: 1 x 2
Ele vai procurar jogos que tenham essa configuração, independente do time e tempo, e vai apostar.
