### ISSUE TITLE
Erro de Tipagem, da um look mano tuple[str]: TypeError: 'type' object is not subscriptable 

### ISSUE THREAD

**Issue by yurifoxxofficial** [JDaniloC/Individual-Bet365Bot#5]
File "C:\Users\user\Desktop\Individual-Bet365Bot-master\Individual-Bet365Bot-master\widgets.py", line 243, in <module>
    def nome_times(wait: WebDriverWait) -> tuple[str]:
TypeError: 'type' object is not subscriptable

**Comment by JDaniloC** [comment]
Isso só funciona no Python 3.9! Pra solucionar isso, eu posso tirar, assim funcionando para python versões antigas...

**Comment by yurifoxxofficial** [comment]
Parceiro, eu tenho muito interesse em te ajudar no que precisar ... eu
Consegui corrigir pro 3.8 importando a biblioteca Typing .. O sistema parou
de dar erro mas tambem nao retorna nenhuma mensagem rsrs

Danilo Silva ***@***.***> escreveu no dia quinta, 1/04/2021
à(s) 20:11:

**Comment by JDaniloC** [comment]
Eu não usei a biblioteca typing justamente por que é nativo do Python 3.9, irei ver o projeto hoje, e melhorar a documentação.
